[project]
name = "task-tracker-cli"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pydantic>=2.12.3",
    "typer>=0.20.0",
]
